/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains  the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"




//==============================================================================
TruePan_0_01AudioProcessor::TruePan_0_01AudioProcessor()
{
    ///////  I/O   ///////////
    UserParams[Gain] = 0.0;
    
    ///////  I/O   ///////////
}

TruePan_0_01AudioProcessor::~TruePan_0_01AudioProcessor()
{

}

//==============================================================================
const String TruePan_0_01AudioProcessor::getName() const
{
    return JucePlugin_Name;
}

bool TruePan_0_01AudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool TruePan_0_01AudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool TruePan_0_01AudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double TruePan_0_01AudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int  TruePan_0_01AudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int TruePan_0_01AudioProcessor::getCurrentProgram()
{
    return 0;
}

void TruePan_0_01AudioProcessor::setCurrentProgram (int index)
{
}

const String TruePan_0_01AudioProcessor::getProgramName (int index)
{
    return String();
}

void TruePan_0_01AudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void TruePan_0_01AudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
    mSampleRate = getSampleRate();
    
}

void TruePan_0_01AudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void TruePan_0_01AudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{

    
    for(int i = getNumInputChannels(); i < getNumOutputChannels(); i++){
        
        //buffer.clear(i, 0, buffer.getNumSamples()); // causing noise!!!!!!!!!!!!!!!!!!
        
    }
    
    int numberOfChannels =  getNumInputChannels();
    
    
    if (numberOfChannels == 2)
    {
        // samples0 = Right, samples1 = Left
        float* samples0 = buffer.getWritePointer(0);
        float* samples1 = buffer.getWritePointer(1);
        
        int n = 0;
        
        
        
        while (n < buffer.getNumSamples())
        {
            
            bufferDelayL[ndelay] = samples1[n];
            bufferDelayR[ndelay] = samples0[n];
            
            delayL = ndelay + delaySamplesPtr[0];
            delayR = ndelay + delaySamplesPtr[1];
            // Somewhere here it will overflow if delaySamplesPtr[] is larger than bufferDelayL.size or R
            if (delayL > 1023)//Buffer size. TODO: abstract.
            {
                delayL -= 1023;
            }
            if (delayR > 1023)
            {
                delayR -= 1023;
            }
            
            // Actual output
            //*samples1++ = bufferDelayL[delayL];
            //*samples0++ = bufferDelayR[delayR];
            samples1[n] = bufferDelayL[delayL];
            samples0[n] = bufferDelayR[delayR];
            
            ndelay++;
            n++;
            
            if (ndelay > 1023)//bufferDelayL.size())
            {
                
                ndelay = 0;
                
            }
            
        }
        
    }

}

//==============================================================================
bool TruePan_0_01AudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* TruePan_0_01AudioProcessor::createEditor()
{
    return new TruePan_0_01AudioProcessorEditor ( *this );
}

//==============================================================================
void TruePan_0_01AudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void TruePan_0_01AudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new TruePan_0_01AudioProcessor();
}
